apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: inventory-config    # load all keys from ConfigMap as env vars
            - secretRef:
                name: inventory-secret    # load all keys from Secret as env vars
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: DB_NAME
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # where Postgres stores data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d  # SQL files here run on first start
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc               # use the PVC we defined
        - name: initdb
          configMap:
            name: postgres-initdb                 # mount the SQL init script from ConfigMap
