apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-secret
  namespace: inventory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: inventory-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: k8s-ops-lab/inventory/db-password
        property: DB_PASSWORD
