apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          # ArgoCD's Kustomize override
          image: notifier:7da166a31903d865e9cda499d0ddeafb38bf8c1c
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          env:
            - name: SERVICE_NAME
              value: "notifier-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
